### ISSUE TITLE
Todo Edit - sync with MongoDB - gives E11000 duplicate key error index

### ISSUE THREAD

**Issue by anupsaund** [strongloop/loopback-example-offline-sync#59] opened 2015-03-25 14:49 UTC
## Issue Overview

I forked the loopback-example-full-stack and then created a datasource for mongoDB - mongo version 3.0.1.
Then i changed the todo model to use mongodb as a datasource.

Creating and deleting a todo works OK - but if I try to edit a Todo I get a duplicate key error;

MongoError: E11000 duplicate key error index: test.Todo.$_id_ dup key: { : "t-2159" }

## Forked at

https://github.com/anupsaund/loopback-example-full-stack

## One commit

https://github.com/anupsaund/loopback-example-full-stack/commit/a8ea1a4f68bda75cbfc5dd0426d21a1a0f715029

## Screenshot

![todoedit](https://cloud.githubusercontent.com/assets/6728822/6827146/ba69e134-d2fd-11e4-8b10-34c41304f425.PNG)

**Comment by superkhau** [comment] 2015-03-26 01:35
Did you try clearing out your database? I've verified that the edit feature doesn't seem to be working properly, but I can't reproduce your duplicate id issue.

**Comment by anupsaund** [comment] 2015-03-26 09:18
@superkhau 

I have tried a fresh test, and then tried to show the story in the following screenshots.

## 1. Clear mongo table and app
![empty_table_empty_todo_list](https://cloud.githubusercontent.com/assets/6728822/6843227/d2dcf51c-d398-11e4-8595-b37408bbcddc.PNG)


## 2. Record Added
![record_added](https://cloud.githubusercontent.com/assets/6728822/6843231/df7410da-d398-11e4-99be-eb347cc2d366.PNG)

## 3. Record Edited
![test_edited](https://cloud.githubusercontent.com/assets/6728822/6843235/e7aa6c90-d398-11e4-8fcf-e188103fd9eb.PNG)

**Comment by bajtos** [comment] 2015-03-26 09:52
This is most likely a bug in the replication algorithm that have been fixed on loopback master. We should verify after a new version of the following modules was released: loopback, loopback-datasource-juggler, loopback-connector-mongodb.

**Comment by anupsaund** [comment] 2015-03-26 10:04
@bajtos - I implemented the code change from https://github.com/strongloop/loopback/pull/973

It fixed the errors.

**Comment by superkhau** [comment] 2015-05-14 17:55
These errors should be fixed on master with my latest updates. Closing.

**Closed by superkhau** 2015-05-14 17:55 UTC
Labels: support
